server:
  port: 8043
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: 123456
    # druid 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    #配置初始化大小、最小、最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    #配置获取连接等待超时的时间，配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: true

    #打开PSCache，并且指定每个连接上PSCache的大小，如果用Oracle，开启，MySQL通常关闭
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
    poolPreparedStatements: false
    #maxPoolPreparedStatementPerConnectionSize: 20

    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j

# Redis 数据库索引
#  Jedis在实现上是直连Redis服务，多线程环境下非线程安全，除非使用连接池，为每个 RedisConnection 实例增加物理连接。
#  Lettuce是一种可伸缩，线程安全，完全非阻塞的Redis客户端，多个线程可以共享一个RedisConnection，它利用Netty NIO框架来高效地管理多个连接，从而提供了异步和同步数据访问方式，用于构建非阻塞的反应性应用程序。
  redis:
    database: 1
    host: 192.168.1.26
    port: 16379
    password: 123456
    timeout: 10000ms
    #哨兵模式
    #  sentinel:
    #    master: mymaster
    #    nodes:
    #      - 10.10.55.51:26379
    #      - 10.10.55.51:26380
    #      - 10.10.55.51:26381
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
      shutdown-timeout: 100ms

# mybatis- plus配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号隔开隔开
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#logback日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: /logs


